### ISSUE TITLE
About buscaMinas.py

### ISSUE THREAD

**Issue by Hexajira** [programingfrik/randomPython#1]
Nice job there. I Loved this version of the game as I've always been a fan of it. Just a couple of things I'd like to see on this one. First, It'd be really nice if cells changed color or depth after been clicked, it would make it easier for the player (at least I have to focus more when clicked cells remain the same color as the un-clicked ones). Second, It'd also be nice and helpful to add a feature where the middle button mouse click would open the surronding cells of the one I just clicked.

Hope makes sense! 

<(^_^)>

**Comment by programingfrik** [comment]
Hello! Thanks for the review!

Because you are the one and only fan of the "buscaMinas.py" game I decided to implement your suggestions! so congratulations, I hope you like the modifications made according to your "issue"  or "comment" :+1:
